name: phel-tests

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch: # Supports manual triggering

jobs:
  test-phel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # TODO should be true (default) for CI?
      matrix:
        php: ['8.4', '8.5']
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --no-ansi --no-progress

      - name: Run tests
        run: php -d memory_limit=256M ./vendor/bin/phel test --reporter=junit-xml --output=phel_junit_output.xml

      - name: Upload Phel test results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: phel-test-results-php-${{ matrix.php }}
          path: phel_junit_output.xml
